//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carousels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BibliographicRecord
    {
        public BibliographicRecord()
        {
            this.RecordSets = new HashSet<RecordSet>();
        }
    
        public int BibliographicRecordID { get; set; }
        public int RecordStatusID { get; set; }
        public Nullable<int> RecordOwnerID { get; set; }
        public int CreatorID { get; set; }
        public Nullable<int> ModifierID { get; set; }
        public string BrowseAuthor { get; set; }
        public string BrowseTitle { get; set; }
        public string BrowseCallNo { get; set; }
        public byte DisplayInPAC { get; set; }
        public Nullable<System.DateTime> ImportedDate { get; set; }
        public string MARCBibStatus { get; set; }
        public string MARCBibType { get; set; }
        public string MARCBibLevel { get; set; }
        public string MARCTypeControl { get; set; }
        public string MARCBibEncodingLevel { get; set; }
        public string MARCDescCatalogingForm { get; set; }
        public string MARCLinkedRecordReq { get; set; }
        public string MARCPubDateOne { get; set; }
        public string MARCPubDateTwo { get; set; }
        public string MARCTargetAudience { get; set; }
        public string MARCLanguage { get; set; }
        public string MARCPubPlace { get; set; }
        public Nullable<short> PublicationYear { get; set; }
        public string MARCCreationDate { get; set; }
        public string MARCModificationDate { get; set; }
        public string MARCLCCN { get; set; }
        public string MARCMedium { get; set; }
        public string MARCPublicationStatus { get; set; }
        public bool ILLFlag { get; set; }
        public string MARCCharCodingScheme { get; set; }
        public string SortAuthor { get; set; }
        public string LiteraryForm { get; set; }
        public System.DateTime RecordStatusDate { get; set; }
        public bool ModifiedByAuthorityJob { get; set; }
        public Nullable<byte> PrimaryMARCTOMID { get; set; }
        public Nullable<System.DateTime> FirstAvailableDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public int LifetimeCircCount { get; set; }
        public int LifetimeInHouseUseCount { get; set; }
        public string SortTitle { get; set; }
        public int Popularity { get; set; }
        public string ImportedFileName { get; set; }
        public byte BrowseTitleNonFilingCount { get; set; }
        public string ImportedControlNumber { get; set; }
        public string ImportedRecordSource { get; set; }
        public bool HasElectronicURL { get; set; }
        public bool DoNotOverlay { get; set; }
    
        public virtual ICollection<RecordSet> RecordSets { get; set; }
    }
}
