//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carousels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BibliographicISBNIndex
    {
        public int BibliographicISBNIndexID { get; set; }
        public int BibliographicRecordID { get; set; }
        public int BibliographicTagID { get; set; }
        public string ISBNString { get; set; }
        public bool IsValidISBN { get; set; }
        public string ISBNDisplayData { get; set; }
        public int BibliographicRecordBibliographicRecordID { get; set; }
    }
}
