//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carousels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolarisEntities : DbContext
    {
        public PolarisEntities()
            : base("name=PolarisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BibliographicISBNIndex> BibliographicISBNIndexes { get; set; }
        public DbSet<BibliographicRecord> BibliographicRecords { get; set; }
        public DbSet<RecordSet> RecordSets { get; set; }
    }
}
